<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWigTzxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWigTzxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWigTzxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWigTzxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWigTzxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WigTzxx',
    'container.build_id' => '0eaa5378',
    'container.build_time' => 1584903739,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWigTzxx');
